(lang dune 3.0)

(name hw_calculator)

(generate_opam_files true)

(package
 (name hw_calculator)
 (allow_empty)
 (depends
  (ocaml (>= 4.14.0))
  dune
  cohttp-lwt-unix
  yojson
  ppx_deriving_yojson
  ppx_fields_conv))