version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - haskell-backend
      - python-backend
    environment:
      - NODE_ENV=development

  haskell-backend:
    build:
      context: ./backend/haskell
      dockerfile: Dockerfile
    ports:
      - "3001:3001"

  python-backend:
    build:
      context: ./backend/python
      dockerfile: Dockerfile
    ports:
      - "3002:3002"

  ocaml-backend:
    build:
      context: ./backend/ocaml
      dockerfile: Dockerfile
    ports:
      - "3003:3003"

  php-backend:
    build:
      context: ./backend/php
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    volumes:
      - ./backend/php:/var/www/html
    environment:
      - PHP_INI_DIR=/usr/local/etc/php